language: csharp
mono: none
dist: trusty
before_install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet-dev-1.0.1
install:
  - dotnet msbuild /t:Clean
  - dotnet msbuild /t:Restore
script:
  - dotnet msbuild /t:Build
  - dotnet test QueryBuilder.Tests/QueryBuilder.Tests.csproj --no-build
